//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.10 at 03:32:56 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zenika.com/camel/notifier/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zenika.camel.notifier.model;
